// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSecret(arg1, arg2) {
  return window['go']['main']['App']['CreateSecret'](arg1, arg2);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetSecrets() {
  return window['go']['main']['App']['GetSecrets']();
}

export function LoadSecret(arg1) {
  return window['go']['main']['App']['LoadSecret'](arg1);
}

export function SaveSecret(arg1, arg2) {
  return window['go']['main']['App']['SaveSecret'](arg1, arg2);
}

export function SetPreference(arg1, arg2) {
  return window['go']['main']['App']['SetPreference'](arg1, arg2);
}
