// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function CreateSecret(arg1:any,arg2:any):Promise<types.Result>;

export function GetPreferences():Promise<types.Preferences>;

export function GetSecrets():Promise<types.ResultList>;

export function LoadSecret(arg1:any):Promise<types.Result>;

export function SaveSecret(arg1:any,arg2:any):Promise<types.Result>;

export function SetPreference(arg1:string,arg2:string):Promise<void>;
