name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            { name: 'SecretEditor', platform: linux/amd64, os: ubuntu-latest },
            {
              name: 'SecretEditor',
              platform: windows/amd64,
              os: windows-latest,
            },
            {
              name: 'SecretEditor',
              platform: darwin/universal,
              os: macos-latest,
            },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '^1.21'
          node-version: '20.x'
