name: Wails build

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            { platform: linux/amd64, os: ubuntu-latest },
            { platform: windows/amd64, os: windows-latest },
            { platform: darwin/universal, os: macos-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Linux deps
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu zip
        shell: bash

      - name: Install Windows deps
        if: runner.os == 'Windows'
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install jq

      - name: Set version
        shell: bash
        run: |
          jq '.info.productVersion = "${{ github.event.release.tag_name }}"' wails.json > tmp.json
          mv tmp.json wails.json
          cd frontend
          jq '.version = "${{ github.event.release.tag_name }}"' package.json > tmp.json
          mv tmp.json package.json

      # Building step
      - name: Build macOS App
        if: runner.os == 'macOS'
        run: wails build --platform ${{matrix.build.platform}} -ldflags "-X main.version=${{ github.event.release.tag_name }}"
        shell: bash

      - name: Build macOS zip file
        if: runner.os == 'macOS'
        shell: bash
        run: ditto -c -k --keepParent ./build/bin/Secret\ Editor.app ./build/bin/SecretEditor_macOS_universal.zip

      - name: Build Linux App
        if: runner.os == 'Linux'
        run: wails build --platform ${{matrix.build.platform}} -o SecretEditor -ldflags "-X main.version=${{ github.event.release.tag_name }}"
        shell: bash

      - name: Build linux zip file
        if: runner.os == 'Linux'
        working-directory: ./build/bin
        shell: bash
        run: zip ./SecretEditor_linux_amd64.zip ./SecretEditor

      - name: Build Windows App
        if: runner.os == 'Windows'
        run: wails build --platform ${{matrix.build.platform}} -o SecretEditor.exe -ldflags "-X main.version=${{ github.event.release.tag_name }}"
        shell: bash

      - name: Build Windows zip file
        if: runner.os == 'Windows'
        working-directory: ./build/bin
        run: Compress-Archive "SecretEditor.exe" "SecretEditor_windows_amd64.zip"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            */bin/*.zip
